CONTRIBUTING.md
contributing.md

#59 - (doc): contributing guidelines

---

.changeset/mighty-guests-listen.md
docs/storybook/.storybook/main.cjs
package.json
packages/editor/.storybook/main.cjs
packages/editor/.storybook/manager.js
packages/editor/.storybook/preview.js
packages/editor/package.json
packages/editor/src/commands.ts
packages/editor/src/editor.scss
packages/editor/src/editor.stories.ts
packages/editor/src/editor.ts
packages/editor/src/index.ts
packages/editor/src/keymap.ts
packages/editor/src/list-utils.ts
packages/editor/src/register.ts
packages/editor/src/schema.ts
packages/editor/src/utils.ts
packages/editor/tsconfig.build.json
packages/editor/tsconfig.json
yarn.lock

- New `@sanomalearning/slds-editor` NPM package
- With `<sl-editor>` web component using prosemirror.net

Add rich text editor component

---

packages/core/src/button/button.ts

Workaround this bug https://github.com/calebdwilliams/element-internals-polyfill/pull/95 for now.

Workaround polyfill bug

---

packages/core/src/form.stories.ts
packages/core/src/input/input.scss
packages/core/src/input/input.spec.ts
packages/core/src/input/input.ts
packages/core/src/label/label.scss
packages/core/src/label/label.spec.ts
packages/core/src/label/label.stories.ts
packages/core/src/label/label.ts

This is the 3rd part split from `feature/input-validation`:
- Add unit tests for `<sl-label>`
- Fix bugs in label implementation wrt required/optional marking

Label improvements

---

.changeset/fast-knives-approve.md
packages/editor/package.json
packages/grid/package.json

The editor & grid packages did not contain any package exports. This fixes that.

Add missing package exports

---

docs/website/src/site/_includes/search.njk
docs/website/src/site/ts/scripts/code-component.ts

 fix/(docs/website) add missing labels

---

.changeset/tough-berries-know.md
packages/components/grid/package.json
packages/components/grid/src/grid.scss
packages/components/grid/src/grid.ts
packages/components/grid/src/stories/scrolling.stories.ts
yarn.lock

- Add missing popover dependency
- Fix border *again*
- Add background color for table header instead of white
- Align header left by default
- Fix row width calculation when there a string present

Various grid fixes

---

.changeset/hip-lies-relate.md

This is an empty PR (other than the changeset), because the previous PR did not mark `@sl-design-system/shared` for release :(

Update `ArrayDataSource` to use custom sort function

---

website/src/site/_data/custom-elements/custom-elements.json
website/src/site/_data/custom-elements/custom-elements.md
website/src/site/_includes/components/components.njk
website/src/site/styles/layout/content.scss

Left the source files for all components because we will be using them in the future. They don't get served/loaded for end-users so they don't impact the website

removed tabs + fixed link colours

---

website/src/categories/components/button/usage.md

Changed description for example to match image #697 
This pull request is direct on sl-disign-system/components

Update - Changed description for example to match image #697

---

.changeset/tidy-months-train.md
packages/components/grid/src/grid.ts

Workaround for https://github.com/lit/lit/issues/4232

Add workaround for virtualizer scrolling bug

---

website/src/categories/whats-new.md

Missing what's new page section about checkbox component

Feature/760 checkbox what's new page section

---

.changeset/slow-cycles-promise.md
packages/components/avatar/custom-elements.json
packages/components/avatar/src/avatar.spec.ts
packages/components/avatar/src/avatar.ts
packages/components/avatar/src/models.ts

Rework avatar to fix change-in-update warnings

---

.changeset/long-eagles-complain.md
packages/components/select/src/select.scss

Fix missing border-radius on select dropdown

---

packages/tokens/src/sanoma-learning/base.json

- put SL theme accordion tokens back

Fix missing accordion tokens

---

.changeset/young-beds-peel.md
packages/components/breadcrumbs/src/breadcrumbs.scss
packages/components/breadcrumbs/src/breadcrumbs.spec.ts
packages/components/breadcrumbs/src/breadcrumbs.stories.ts
packages/components/breadcrumbs/src/breadcrumbs.ts

Refactor breadcrumbs so the links are in an unordered list

---

.changeset/moody-ladybugs-rhyme.md
packages/components/dialog/src/dialog.scss
packages/components/dialog/src/dialog.stories.ts
packages/components/dialog/src/dialog.ts

Fix dialog clipping the focus outline of form fields

---

website/src/categories/getting-started/developers.md

And document the `css` and `scss` folders in the theme packages.

Replace references to `all.css` with `light.css`

---

.changeset/great-mayflies-beg.md
packages/components/accordion/src/accordion.stories.ts
packages/components/avatar/src/avatar.stories.ts
packages/components/badge/src/badge.stories.ts
packages/components/breadcrumbs/src/breadcrumbs.stories.ts
packages/components/button-bar/src/button-bar.stories.ts
packages/components/form/src/form-control-mixin.ts
packages/components/inline-message/src/inline-message.stories.ts
packages/components/search-field/src/search-field.stories.ts
packages/components/search-field/src/search-field.ts
packages/components/text-field/src/text-field.ts
website/src/categories/components/accordion/accordion.json
website/src/categories/components/avatar/avatar.json
website/src/categories/components/badge/badge.json
website/src/categories/components/breadcrumbs/breadcrumbs.json
website/src/categories/components/breadcrumbs/breadcrumbs.md
website/src/categories/components/button-bar/button-bar.json
website/src/categories/components/button-bar/button-bar.md
website/src/categories/components/inline-message/inline-message.json
website/src/categories/components/search-field/code.md
website/src/categories/components/search-field/search-field.json
website/src/categories/components/search-field/search-field.md
website/src/categories/components/search-field/usage.md

This PR will update the versions of the following components to 1.0:
- Accordion
- Avatar
- Badge
- Breadcrumbs
- Button bar
- Inline message
Search-field moves to "Preview".

Release new stable versions

---

.changeset/shaggy-beans-smoke.md
packages/components/tabs/src/tab-group.scss
packages/components/tabs/src/tab-group.stories.ts
packages/components/tabs/src/tab-group.ts

Fix unnecessary padding if there are no tab panels

---

.changeset/famous-peaches-fetch.md
packages/components/breadcrumbs/src/breadcrumbs.scss

Improve breadcrumbs hover state by changing the `text-decoration-thickness`

---

.changeset/witty-cameras-protect.md
packages/components/accordion/src/accordion-item.ts
packages/components/accordion/src/accordion.stories.ts

Make the accordion item summary slottable

---

.changeset/heavy-peaches-bake.md
examples/lit/src/composite-form/composite-form.ts
packages/components/checkbox/src/checkbox-group.ts

Fix error in checkbox group when setting the form value

---

.changeset/four-kids-brush.md
packages/angular/src/package.json

Fix angular dependencies to be on 17 or 18

---

website/src/categories/components/component-table.njk

Do not show static properties in the docs

---

.changeset/cold-chicken-cover.md
packages/tokens/src/teas/base.json

Increased the focus ring thickness in TEAS from 1px to 2px.

updated TEAS focus ring

---

.changeset/many-steaks-retire.md
packages/components/checkbox/src/checkbox-group.spec.ts
packages/components/checkbox/src/checkbox.spec.ts
packages/components/combobox/src/combobox.spec.ts
packages/components/combobox/src/combobox.ts
packages/components/radio-group/src/radio-group.spec.ts
packages/components/radio-group/src/radio-group.ts
packages/components/select/src/select.spec.ts
packages/components/select/src/select.ts
packages/components/switch/src/switch.spec.ts
packages/components/text-area/src/text-area.spec.ts
packages/components/text-field/src/text-field.spec.ts

Clicking a label doesn't always focus the form control

---

.changeset/quiet-ravens-brush.md
packages/components/tooltip/src/tooltip-directive.spec.ts
packages/components/tooltip/src/tooltip-directive.ts
packages/components/tooltip/src/tooltip.ts

Fix lazy tooltip creation bug

---

.github/workflows/chromatic.yml
.github/workflows/website.yml

Some versions we were using are going to be deprecated/disabled in january.

Update github actions

---

.changeset/flat-guests-know.md
packages/components/grid/src/column-group.spec.ts
packages/components/grid/src/grid.ts
packages/components/grid/src/stories/basics.stories.ts

Fix timing issue in grid where the column width was never calculated

---

website/src/categories/components/badge/accessibility.md

Fix badge `aria-label` documentation

---

.changeset/ripe-forks-lead.md
packages/components/checkbox/src/checkbox-group.ts
packages/components/checkbox/src/checkbox.ts
packages/components/data-source/src/data-source.ts
packages/components/form/src/form-controller.ts
packages/components/form/src/form.ts
packages/components/grid/src/column-group.ts
packages/components/grid/src/select-column.ts
packages/components/message-dialog/src/message-dialog.ts
packages/components/radio-group/src/radio-group.ts
packages/components/radio-group/src/radio.ts
packages/components/shared/src/events/change.ts
packages/components/shared/src/events/select.ts
packages/components/shared/src/events/toggle.ts
packages/components/switch/src/switch.ts

Replace generic `unknown` type with `any` to be more forgiving for users

---

.changeset/dark-aliens-invent.md
packages/components/combobox/src/combobox.ts
packages/components/tag/src/tag-list.spec.ts
packages/components/tag/src/tag-list.ts

Various combobox fixes

---

.changeset/metal-chicken-stop.md
packages/components/listbox/src/option.spec.ts
packages/components/listbox/src/option.ts

Add missing `textContent` setter

---

.changeset/icy-islands-ring.md
packages/components/grid/src/grid.scss

Fix colors on hover/active clickable grid rows

---

.changeset/swift-pandas-repeat.md
packages/components/radio-group/src/radio-group.scss

Increase gap between radio buttons in horizontal mode

fix/ 2001 Padding in the radio group - horizontal

---

.changeset/huge-taxis-say.md
packages/components/tabs/src/tab-group.scss
packages/components/tabs/src/tab-group.stories.ts

use mask-image with inherited bg instead of background gradient with explicit colour

fix/1999 Add possibility to change background color for tab bar

---

.changeset/public-trams-obey.md
.changeset/ripe-doors-help.md
packages/components/data-source/src/list-data-source.ts
packages/components/grid/src/grid.ts
packages/components/grid/src/stories/selection.stories.ts

Fix bugs related to group selection in grid

---

.changeset/gentle-phones-cover.md
packages/components/grid/src/grid.ts

Reset the grid selection when the data source is replaced

---

.changeset/modern-dots-invite.md
packages/components/tool-bar/src/tool-bar.scss

fix: change toolbar background to transparent

---

website/src/categories/components/tag/accessibility.md

Fix tag documentation
