.changeset/nice-poets-hope.md, packages/core/package.json, packages/core/src/dialog/dialog.scss, packages/core/src/utils/controllers/selection.ts, packages/core/src/utils/data-source/array-data-source.ts, packages/core/src/utils/data-source/data-source.ts, packages/core/src/utils/data-source/index.ts, packages/core/src/utils/index.ts, packages/core/src/utils/path.ts, packages/grid/src/column.ts, packages/grid/src/grid.stories.ts, packages/grid/src/grid.ts, packages/grid/src/index.ts, packages/grid/src/register.ts, packages/grid/src/sort-column.ts, packages/grid/src/sorter.scss, packages/grid/src/sorter.ts
- Add `@sanomalearning/utils/data-source` with `ArrayDataSource`
- Add `dataSource` property to `Grid` and use that for filtering & sorting
- Add `<sl-grid-sort-column>` for sortable columns
- Fix dialog backdrop blur in Safari
=> Add sortable columns to grid

.changeset/thirty-meals-sell.md, packages/core/.storybook/main.js, packages/core/package.json, packages/core/src/label/index.ts, packages/core/src/label/label.scss, packages/core/src/label/label.stories.ts, packages/core/src/label/label.ts, packages/core/src/label/register.ts
New `<sl-label>` web component for:
- Automatic styling of labels using design tokens
- Automatic adding of required or optional indicators based on UX rules: if the majority of the fields in the form are optional, then show the required fields and the other way around
- Actual `<label>` is still in Light DOM, so fully accessible
=> Add label component

packages/core/.storybook/preview.js, packages/core/lit-localize.json, packages/core/package.json, packages/core/src/locales/locale-codes.ts, packages/core/src/locales/nl.ts, packages/core/src/locales/nl.xlf, yarn.lock
This is another part split from the `feature/input-validation` branch
- Add English and Dutch locales to core
- Add localisation switcher to core storybook
=> Add support for localization

.changeset/itchy-donkeys-fly.md, packages/core/package.json, packages/core/src/input/input.stories.ts, packages/core/src/input/input.ts, packages/core/src/radio-group/radio-group.scss, packages/core/src/radio-group/radio-group.stories.ts, packages/core/src/radio-group/radio-group.ts, packages/core/src/radio-group/radio.ts, packages/core/src/textarea/textarea.ts, packages/core/src/utils/form-control/hint-mixin.spec.ts, packages/core/src/utils/form-control/hint-mixin.ts, packages/core/src/utils/form-control/index.ts
This part has been split from the `feature/input-validation` branch:
- Adds `HintMixin` from `@sanomalearning/slds-core/utils/form-control`
- Add mixin to input, textarea and radio-group
=> Add `HintMixin` for use in form controls

.changeset/moody-parents-grin.md, packages/components/checkbox/src/checkbox.scss, packages/components/checkbox/src/checkbox.stories.ts, packages/components/checkbox/src/checkbox.ts
- Check if there is a label present and add a `no-label` attribute if there isn't
- Hide `.label` when `no-label` attribute it present
- Add left padding when there is no label present
- Split padding into `block` and `inline`
- Adjust gap to take inline padding into account
- Move padding from the outer element to the actual click target
- Fix vertical alignment of label bug
Fixes #390
=> Fix checkbox being too big when there is no label

.changeset/perfect-feet-raise.md, packages/components/grid/register.ts, packages/components/grid/src/column.ts, packages/components/grid/src/filter-column.ts, packages/components/grid/src/filter.ts, packages/components/grid/src/grid.ts, packages/components/grid/src/selection-column.ts, packages/components/grid/src/sorter.ts
- Fix unexported filter types
- Add `GridColumnAlignment` type
- Add `itemsChanged()` callback for when the items in the grid have changed
- Fix name of sorter direction change event to match other events
- Fix initial checked state in selection column header
=> Fix various grid issues

.changeset/great-socks-sing.md, packages/components/grid/src/grid.scss, packages/components/grid/src/grid.ts, packages/components/grid/src/stories/basics.stories.ts, tools/example-data/index.d.ts
This works around an issue with `@lit-labs/virtualizer` where it does not take the border-width into account when calculating the `min-height`. This is also related to us using `box-sizing: border-box`, but due to styling, we cannot remove that.
=> Fix tbody min-height not taking the border width into account

.changeset/sharp-grapes-shout.md, .changeset/smart-trainers-shout.md, packages/components/grid/register.ts, packages/components/grid/src/column-group.ts, packages/components/grid/src/column.ts, packages/components/grid/src/filter-column.ts, packages/components/grid/src/filter.ts, packages/components/grid/src/grid.ts, packages/components/grid/src/sort-column.ts, packages/components/grid/src/sorter.ts
- Add `position="bottom"` to filter popover so it does not appear below a sticky header above it in browsers that do not support popover yet
- Use explicit grid events instead of `CustomEvent`. Allows us to add a `column` property for column related events.
=> Various grid fixes

.changeset/early-waves-smell.md, packages/components/dialog/src/dialog.scss
Without this fix, content in the dialog cannot overflow the boundaries of the dialog, like in the screenshot.
=> Fix dialog overflow to be visible instead of the default hidden

.changeset/modern-maps-mate.md, packages/components/badge/package.json, packages/components/breadcrumbs/package.json, packages/components/button-bar/package.json, packages/components/card/package.json, packages/components/checkbox/package.json, packages/components/dialog/package.json, packages/components/drawer/package.json, packages/components/editor/package.json, packages/components/form/package.json, packages/components/grid/package.json, packages/components/icon/package.json, packages/components/inline-message/package.json, packages/components/menu/package.json, packages/components/message-dialog/package.json, packages/components/radio-group/package.json, packages/components/select/package.json, packages/components/shared/package.json, packages/components/skeleton/package.json, packages/components/spinner/package.json, packages/components/switch/package.json, packages/components/tabs/package.json, packages/components/text-field/package.json, packages/components/textarea/package.json, packages/components/tooltip/package.json, yarn.lock
Previously we had 3rd party component dependencies as `dependencies` in their respective `package.json` files. This can cause issues when used in applications, because the components will not use the same dependencies from the application. For example, runtime translations are broken because components have their own version of `@lit/localize` which does not have the translations as configured by the application.
By making those 3rd party dependencies `peerDependencies`, this is fixed.
=> Fix 3rd party component dependencies to be peerDependencies instead

.changeset/mighty-dryers-exist.md, packages/components/grid/src/filter.ts, packages/components/grid/src/stories/filtering.stories.ts
When a grid includes both a selection column and a filter column, a potential issue may arise. If you select a filter and then proceed to check a checkbox in the selection column, subsequently deselecting it, the checked status of the filtered item might not be visible. However, the filtering functionality remains intact.
Fixed it by changing ?checked to .checked since it should have the same effect, as both the property and attribute control whether the checkbox is checked or not.
=> fixed checkbox checked value

packages/checklist/index.ts, packages/checklist/package.json, packages/checklist/src/checklist.stories.ts, packages/checklist/src/checklist.ts, yarn.lock
Mainly to fix `<slds-checklist>` being tree-shaken away in the storybook build.
=> Checklist fixes

.changeset/three-lamps-dream.md, packages/components/popover/src/popover.scss
The `margin: 0;` reset was missing from sl-popover.
=> Fix popover positioning in FF & Safari

CONTRIBUTING.md, website/src/categories/getting-started/developers.md
When implementing the `sl-button` in `max-online`, we encountered lots of errors stating `this.attachInternals is not a function`. 
Polyfill [element-internals-polyfill](https://www.npmjs.com/package/element-internals-polyfill) is needed to solve this for older browsers. See also https://caniuse.com/mdn-api_elementinternals
=> Improve getting started, polyfills section

.changeset/dry-jokes-sit.md, scripts/build-themes.js
Some transformations were not being applied to the files in `@sl-design-system/<theme>/css` and `@sl-design-system/<theme>/scss`, like the `wrapMathInCalc` transform. This resulted in styling errors when using these files. The light/dark files do not have this bug.
=> Fix missing `calc()` functions in theme parts.

.changeset/thin-apricots-wonder.md, packages/components/form/src/form-control-mixin.ts, packages/components/text-field/src/text-field.spec.ts
Do not set the `formControlElement` variable to `undefined` on disconnect. This prevents errors in unit tests from happening due to async code.
=> Fix error when querying form control state after disconnect

.changeset/angry-mails-pretend.md, .changeset/clever-bees-shop.md, packages/angular/src/forms/text-field.directive.ts, packages/components/search-field/src/search-field.ts, packages/components/text-field/src/text-field.spec.ts, packages/components/text-field/src/text-field.stories.ts, packages/components/text-field/src/text-field.ts
- Use `T extends { toString(): string } = string` type for `TextField`
- Add `parseValue` method that converts the raw value to the given type (or throw an Error if it cannot be parsed)
- Add `formatValue` method to format a value for display in the input
=> Add a generic type to TextField so we can use that for inheritance

.storybook/manager.ts, .storybook/preview.ts, packages/components/grid/src/stories/basics.stories.ts, packages/components/grid/src/stories/drag-and-drop.stories.ts, packages/components/grid/src/stories/editing.stories.ts, packages/components/grid/src/stories/filtering.stories.ts, packages/components/grid/src/stories/grouping.stories.ts, packages/components/grid/src/stories/scrolling.stories.ts, packages/components/grid/src/stories/selection.stories.ts, packages/components/grid/src/stories/sorting.stories.ts, packages/components/grid/src/stories/styling.stories.ts
Also makes it possible to mark different parts of grid draft/preview/stable.
=> Move grid to a toplevel category in Storybook

.changeset/dull-lemons-sit.md, packages/components/checkbox/src/checkbox-group.spec.ts, packages/components/checkbox/src/checkbox-group.stories.ts, packages/components/checkbox/src/checkbox-group.ts
=> Fix `<sl-checkbox-group>` value not reflecting initial `checked` state

.changeset/lovely-cars-teach.md, packages/angular/src/tooltip.directive.ts, packages/components/breadcrumbs/src/breadcrumbs.ts, packages/components/toggle-button/src/toggle-button.ts, packages/components/tooltip/src/tooltip-directive.ts
This uses the new cleanup function that is returned from `Tooltip.lazy` to properly cleanup anything added by the tooltip code.
=> Add proper tooltip cleanup

.changeset/lemon-masks-rest.md, tools/eslint-config/index.js
If you are using the `href` *property* instead of the attribute, then `anchor-is-valid` will mark that as incorrect. It doesn't matter if you use the attribute or the property. The value of the property is automatically reflected in the attribute.
=> Disable `lit-a11y/anchor-is-valid` rule for now

.changeset/ninety-comics-poke.md, packages/components/menu/src/menu-button.spec.ts, packages/components/menu/src/menu-button.ts
=> Fix missing initial `aria-expanded` and `aria-details` attributes on the button

.changeset/tough-papayas-sip.md, packages/components/combobox/src/combobox.spec.ts, packages/components/combobox/src/combobox.ts, packages/components/combobox/src/no-match.scss, packages/components/combobox/src/no-match.ts, packages/locales/src/nl.ts, packages/locales/src/nl.xlf
=> Show a message when there are no filter matches in combobox

packages/components/grid/src/filter-column.spec.ts, packages/components/grid/src/filter.ts, packages/components/grid/src/grid.ts
The #1575 PR broke partial matching for `<sl-grid-filter-column mode="text">`. This PR fixes that.
=> Fix regression in filter-column with text mode

.changeset/chilly-coins-attack.md, .changeset/hot-impalas-exercise.md, .changeset/soft-needles-tan.md, .changeset/ten-lies-drive.md, packages/components/button/src/button.spec.ts, packages/components/button/src/button.ts, packages/components/form/src/examples.stories.ts, packages/components/form/src/form-control-mixin.ts, packages/components/form/src/form.spec.ts, packages/components/form/src/form.ts, packages/components/shared/src/dom.ts, packages/components/text-field/src/text-field.spec.ts, packages/components/text-field/src/text-field.ts
- Implement reset & submit behavior in `<button>` when there is only an `<sl-form>` parent present
- Implement submit behavior in `<sl-text-field>` when there is only an `<sl-form>` parent present
- Add `sl-reset` and `sl-submit` events on `<sl-form>`
- Fix bug where resetting a form did not clear the validation messages
- Add `closestElementComposed` utility method to shared package
Fixes #1566
=> Improve form integration

.github/workflows/ci.yml, .github/workflows/release.yml, .github/workflows/storybook.yml, .github/workflows/website.yml, package.json, web-test-runner.config.mjs, yarn.lock
- Update playwright so it works on Ubuntu 24 (now the default on GitHub Actions)
- Update node.js from 20 to 22 (not LTS)
- Update `@web/test-runner` config to explicitly set the locale to `en` (fixes issue with playwright chromium build)
=> Update settings & dependencies for CI

.changeset/floppy-tires-marry.md, packages/components/select/src/select.ts
=> Log a warning when you use `<sl-select>` without having `<sl-option>` registered

.changeset/five-cars-call.md, packages/components/listbox/src/listbox.ts, packages/components/shared/src/controllers/focus-group.ts, packages/components/tree/src/tree.ts
=> Fix `@lit-labs/lit-virtualizer` imports to not accidentally register `<lit-virtualizer>` on the global custom element registry

.changeset/fancy-lies-kiss.md, packages/angular/package.json, packages/angular/src/forms/checkbox-group.directive.ts, packages/angular/src/forms/checkbox.directive.ts, packages/angular/src/forms/form-control-element.directive.ts, packages/angular/src/forms/number-field.directive.ts, packages/angular/src/forms/public-api.ts, packages/angular/src/forms/radio-group.directive.ts, packages/angular/src/forms/select.directive.ts, packages/angular/src/forms/switch.directive.ts, packages/angular/src/forms/text-area.directive.ts, packages/angular/src/forms/text-field.directive.ts, packages/angular/src/package.json, packages/angular/stories/forms.stories.ts, packages/angular/stories/wrappers.stories.ts, packages/components/number-field/src/number-field.spec.ts, packages/components/number-field/src/number-field.ts, yarn.lock
=> Add support for `<sl-number-field>` to the Angular bindings

.changeset/rich-ravens-shout.md, packages/components/tool-bar/src/tool-bar.spec.ts, packages/components/tool-bar/src/tool-bar.stories.ts, packages/components/tool-bar/src/tool-bar.ts
=> Fix disabled state of tool bar buttons not being reflected in menu items

.changeset/bitter-masks-float.md, packages/components/tool-bar/src/tool-bar.spec.ts, packages/components/tool-bar/src/tool-bar.stories.ts, packages/components/tool-bar/src/tool-bar.ts
=> Add support for `<sl-menu-button>` to `<sl-tool-bar>`

.changeset/eleven-beers-pump.md, packages/components/select/src/select.scss
The moment you close the popover it moves back from the toplayer to the actual parent node. But that of course is translated, so it moves along with that translation and jump to another spot.
To make sure the popover isn't removed from the toplayer until the animations are finished you can add overlay to the list of transition-properties, but https://github.com/web-platform-tests/interop/issues/1031.
For now we will not put in more effort to fix this issue, since it's cosmetic and only occurs when one of the parents of the select is translated, and then only in safari.
=> Fix: Add 'overlay' to transition properties for sl-listbox
